- hosts: localhost
  tasks:
  - name: Create a network docker
    docker_network:
    name: esnet
    
  - name: Wait untils Jenkins web API is available
    shell: curl --head --silent http://localhost:8080/cli/
    register: result
    until: result.stdout.find("200 OK") != -1
    retries: 12
    delay: 5
    
  - name: Restart Jenkins service and enable on boot
    service:
      name: jenkins
      state: restarted
      enabled: yes

  - name: Wait untils Jenkins web API is available
    shell: curl --head --silent http://localhost:8080/cli/
    register: result
    until: result.stdout.find("200 OK") != -1
    retries: 12
    delay: 5

  - jenkins_job:
      config: "{{ lookup('file', 'jobs/jobmaven.xml') }}"
      name: job_maven
      url: http://localhost:8080
      user: admin
      password: tidax
      
  - jenkins_job:
      config: "{{ lookup('file', 'jobs/jmeter.xml') }}"
      name: jmetter-demo
      url: http://localhost:8080
      user: admin
      password: tidax
